### ISSUE TITLE
my notifyAlertSMS is error with nil~ in v2.21

### ISSUE THREAD

**Issue by hung1806vn** [N3MTV/gcphone#199]
Error running call reference function for resource esx_addons_gcphone: citizen:/scripting/lua/scheduler.lua:405: @esx_addons_gcphone/server.lua:22: attempt to concatenate a nil value (field 'y')
stack traceback:
        @esx_addons_gcphone/server.lua:22: in function 'notifyAlertSMS'
        @esx_addons_gcphone/server.lua:144: in upvalue 'callback'
        @esx_addons_gcphone/server.lua:133: in upvalue 'ref'
        citizen:/scripting/lua/scheduler.lua:391: in function <citizen:/scripting/lua/scheduler.lua:390>
        [C]: in function 'xpcall'
        citizen:/scripting/lua/scheduler.lua:390: in function <citizen:/scripting/lua/scheduler.lua:389>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:405: in function <citizen:/scripting/lua/scheduler.lua:374>
Error: Unhandled error in timer: Error: BUFFER_SHORTAGE
Error: BUFFER_SHORTAGE
    at n.e [as reserve] (citizen:/scripting/v8/msgpack.js:29:12766)
    at h (citizen:/scripting/v8/msgpack.js:29:15761)
    at n.r [as decode] (citizen:/scripting/v8/msgpack.js:29:13908)
    at n.fetch (citizen:/scripting/v8/msgpack.js:29:6972)
    at n.u [as read] (citizen:/scripting/v8/msgpack.js:29:12076)
    at Object.n [as decode] (citizen:/scripting/v8/msgpack.js:29:7097)
    at unpack (citizen:/scripting/v8/main.js:20:33)
    at citizen:/scripting/v8/main.js:51:20
    at setImmediate (mysql-async.js:4962:9)
    at Object.callback (citizen:/scripting/v8/timer.js:96:21)

**Comment by wolgix** [comment]
How to fix??

**Comment by heyheyitsmeman** [comment]
I wonder the same thing? How to fix?
