### ISSUE TITLE
gcphone npm run build error

### ISSUE THREAD

**Issue by ahmetalii** [N3MTV/gcphone#221]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build',
1 verbose cli   '--report' ]
2 info using npm@6.9.0
3 info using node@v10.16.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle src_htmlphone@1.0.0~prebuild: src_htmlphone@1.0.0
6 info lifecycle src_htmlphone@1.0.0~build: src_htmlphone@1.0.0
7 verbose lifecycle src_htmlphone@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle src_htmlphone@1.0.0~build: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\fivemserver\cfx-server-data-master\resources\gcphoness\src_htmlPhone\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\nodejs\;C:\Users\ahmet\AppData\Local\Microsoft\WindowsApps;C:\Users\ahmet\AppData\Roaming\npm;C:\Users\ahmet\AppData\Local\Programs\Microsoft VS Code\bin
9 verbose lifecycle src_htmlphone@1.0.0~build: CWD: D:\fivemserver\cfx-server-data-master\resources\gcphoness\src_htmlPhone
10 silly lifecycle src_htmlphone@1.0.0~build: Args: [ '/d /s /c', 'node build/build.js' ]
11 silly lifecycle src_htmlphone@1.0.0~build: Returned: code: 1  signal: null
12 info lifecycle src_htmlphone@1.0.0~build: Failed to exec build script
13 verbose stack Error: src_htmlphone@1.0.0 build: `node build/build.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid src_htmlphone@1.0.0
15 verbose cwd D:\fivemserver\cfx-server-data-master\resources\gcphoness\src_htmlPhone
16 verbose Windows_NT 10.0.17134
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build" "--report"
18 verbose node v10.16.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error src_htmlphone@1.0.0 build: `node build/build.js`
22 error Exit status 1
23 error Failed at the src_htmlphone@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

I have encountered this problem, do you have any solution

**Comment by insayd10** [comment]
reinstall node try force
