### ISSUE TITLE
Error running call reference function for resource esx_addons_gcphone

### ISSUE THREAD

**Issue by wolgix** [N3MTV/gcphone#260]
Everyting works well, but i see this error in console.

Error running call reference function for resource esx_addons_gcphone: citizen:/scripting/lua/scheduler.lua:355: @esx_addons_gcphone/server.lua:22: attempt to concatenate a nil value (field 'y')
stack traceback:
	@esx_addons_gcphone/server.lua:22: in function 'notifyAlertSMS'
	@esx_addons_gcphone/server.lua:144: in upvalue 'callback'
	@esx_addons_gcphone/server.lua:133: in upvalue 'ref'
	citizen:/scripting/lua/scheduler.lua:341: in function <citizen:/scripting/lua/scheduler.lua:340>
	[C]: in function 'xpcall'
	citizen:/scripting/lua/scheduler.lua:340: in function <citizen:/scripting/lua/scheduler.lua:339>
stack traceback:
	[C]: in function 'error'
	citizen:/scripting/lua/scheduler.lua:355: in function <citizen:/scripting/lua/scheduler.lua:324>

**Comment by wolgix** [comment]
Please heelp :(

**Comment by wolgix** [comment]
Error running call reference function for resource esx_addons_gcphone: citizen:/scripting/lua/scheduler.lua:355: @esx_addons_gcphone/server.lua:22: attempt to concatenate a nil value (field 'y')
stack traceback:
	@esx_addons_gcphone/server.lua:22: in function 'notifyAlertSMS'
	@esx_addons_gcphone/server.lua:144: in upvalue 'callback'
	@esx_addons_gcphone/server.lua:133: in upvalue 'ref'
	citizen:/scripting/lua/scheduler.lua:341: in function <citizen:/scripting/lua/scheduler.lua:340>
	[C]: in function 'xpcall'
	citizen:/scripting/lua/scheduler.lua:340: in function <citizen:/scripting/lua/scheduler.lua:339>
stack traceback:
	[C]: in function 'error'
	citizen:/scripting/lua/scheduler.lua:355: in function <citizen:/scripting/lua/scheduler.lua:324>
Error: Unhandled error in timer: Error: BUFFER_SHORTAGE
Error: BUFFER_SHORTAGE
    at n.e [as reserve] (citizen:/scripting/v8/msgpack.js:29:12766)
    at h (citizen:/scripting/v8/msgpack.js:29:15761)
    at n.r [as decode] (citizen:/scripting/v8/msgpack.js:29:13908)
    at n.fetch (citizen:/scripting/v8/msgpack.js:29:6972)
    at n.u [as read] (citizen:/scripting/v8/msgpack.js:29:12076)
    at Object.n [as decode] (citizen:/scripting/v8/msgpack.js:29:7097)
    at unpack (citizen:/scripting/v8/main.js:20:33)
    at citizen:/scripting/v8/main.js:51:20
    at setImmediate (mysql-async.js:14431:7)
    at Object.callback (citizen:/scripting/v8/timer.js:96:21)

**Comment by wolgix** [comment]
:(

**Comment by wolgix** [comment]
haaalp
